### ISSUE TITLE
error upgrading from 0.2.3 to 0.2.4

### ISSUE THREAD

**Issue by ashirai** [aurelia/i18n#20]
After upgrading aurelia-i18n from 0.2.2 to 0.2.4, I am getting this error. 
Unhandled promise rejection TypeError: this.lazyParams is not a function
If I downgrade it from 0.2.4 to 0.2.3, it works just fine.

**Comment by zewa666** [comment]
Can you reproduce this error or does it only happen from time to time? If first one please create a Plunkr or simply setup a clone of the skeleton with i18n version 0.2.4 depicting the problem.

**Comment by ashirai** [comment]
Yes, I can reproduce it every time.  This is what I noticed. I had a line of code like this: <span t="save"></span>, and if I replace it with <span>${i18n.tr("save")}</span>, it works just fine. Again in version of 0.2.3, <span t="save"></span> works without any problem but in 0.2.4, t="..." doesn't seem to work anymore. I confirmed that I have no other changes besides what I mentioned above.

**Comment by zewa666** [comment]
@ashirai can you verify that this happens with the latest tag 0.2.6 as well? If so please create a clone repository with the example depicting the problem as I cannot reproduce it.

**Comment by ashirai** [comment]
@zewa666, thank you, that fixed it!

**Comment by zewa666** [comment]
Glad to hear that
